-- Drop tables in the correct order to handle foreign key dependencies
DROP TABLE Flown_By;
DROP TABLE Assigned_To;
DROP TABLE Aircraft;
DROP TABLE Supply;
DROP TABLE Flight;
DROP TABLE Base;
DROP TABLE Mission;
DROP TABLE Soldier;
DROP TABLE Owns CASCADE CONSTRAINTS;
DROP TABLE Supplier CASCADE CONSTRAINTS;
DROP TABLE Stores CASCADE CONSTRAINTS;
DROP TABLE Supplies CASCADE CONSTRAINTS;
DROP TABLE Storeman CASCADE CONSTRAINTS;
DROP TABLE Item CASCADE CONSTRAINTS;
DROP TABLE Weapon CASCADE CONSTRAINTS;
DROP TABLE Uniform CASCADE CONSTRAINTS;
