ALTER TABLE STORES
DROP COLUMN TEMP_RN;

ALTER TABLE BASE
DROP COLUMN TEMP_RN;

ALTER TABLE STORES
DROP COLUMN BASE_ID;

ALTER TABLE STORES DROP CONSTRAINT fk_store_base;

-- Step 1: Add the row_num column to the STORES and BASE tables
ALTER TABLE STORES
ADD TEMP_RN INTEGER;

ALTER TABLE BASE
ADD TEMP_RN INTEGER;

-- Step 2: Populate the row_num column with index values
UPDATE STORES
SET TEMP_RN = ROWNUM;

UPDATE BASE
SET TEMP_RN = ROWNUM;

-- Step 3: Add the BASE_ID column to the STORES table
ALTER TABLE STORES
ADD BASE_ID INTEGER;

-- Step 4: Populate the BASE_ID column with keys from base
UPDATE STORES s
SET s.BASE_ID = (
    SELECT b.BASE_ID
    FROM BASE b
    WHERE b.TEMP_RN = s.TEMP_RN
);

-- step 5: Add foreign key constraints
ALTER TABLE STORES
ADD CONSTRAINT fk_store_base
FOREIGN KEY (base_id)
REFERENCES BASE(BASE_ID);

-- step 6:drop temporary columns
ALTER TABLE STORES
DROP COLUMN TEMP_RN;

ALTER TABLE BASE
DROP COLUMN TEMP_RN;

SELECT * from STORES
