insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (104356, 'Aluf', 'Ophelie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (759045, 'Aluf', 'Jo');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (581137, 'Aluf Mishne', 'Federico');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (815715, 'Tat Aluf', 'Gordie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (650522, 'Tat Aluf', 'Cornall');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (195481, 'Sgan Aluf Bakhir', 'Clemens');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (272590, 'Sgan Aluf Bakhir', 'Duff');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (589796, 'Aluf', 'Astra');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (672691, 'Tzir Aluf', 'Caprice');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (965547, 'Tat Aluf', 'Clemmy');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (237825, 'Aluf Mishne', 'Frankie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (668519, 'Aluf', 'Carolina');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (829485, 'Aluf', 'Lotti');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (333699, 'Aluf Mishne', 'Jeramie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (393976, 'Tzir Aluf', 'Myra');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (198627, 'Sgan Aluf Mishne', 'Karita');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (531452, 'Seren', 'Edita');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (341474, 'Sgan Aluf Bakhir', 'Xerxes');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (618501, 'Sgan Aluf Mishne', 'Udell');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (501338, 'Tzir Aluf', 'Brion');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (647368, 'Rav Seren', 'Dun');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (685210, 'Aluf Mishne', 'Tabbatha');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (718804, 'Aluf Mishne', 'Sari');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (610727, 'Sgan Aluf', 'Quent');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (488522, 'Sgan Aluf Mishne', 'Carolee');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (132451, 'Seren', 'Letty');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (562865, 'Aluf Mishne', 'Fair');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (977901, 'Rav Seren', 'Sarena');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (629763, 'Rav Seren', 'Jess');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (130618, 'Seren', 'Quinta');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (670816, 'Tzir Aluf', 'Rosemary');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (505269, 'Sgan Aluf Mishne', 'Ingeberg');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (193307, 'Aluf Mishne', 'Eleonore');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (592974, 'Seren', 'Shannan');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (532198, 'Sgan Aluf Bakhir', 'Dane');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (473382, 'Sgan Aluf Mishne', 'Shanie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (928842, 'Sgan Aluf', 'Selina');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (953947, 'Aluf', 'Elmo');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (164754, 'Rav Seren', 'Karlen');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (291526, 'Aluf', 'Samuel');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (113704, 'Aluf', 'Alta');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (375348, 'Sgan Aluf Mishne', 'Brandon');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (108225, 'Rav Seren', 'Tailor');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (366822, 'Sgan Aluf', 'Alain');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (179764, 'Tat Aluf', 'Andriana');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (131095, 'Seren', 'Ileane');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (785490, 'Aluf', 'Giustino');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (732766, 'Sgan Aluf', 'Rodrick');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (577750, 'Tat Aluf', 'Wynne');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (687918, 'Tzir Aluf', 'Hedda');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (398275, 'Sgan Aluf Bakhir', 'Isadore');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (578208, 'Aluf Mishne', 'Emyle');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (606273, 'Seren', 'Tedmund');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (152767, 'Rav Seren', 'Cull');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (425110, 'Aluf Mishne', 'Garrett');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (660795, 'Sgan Aluf Mishne', 'Marne');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (947560, 'Tzir Aluf', 'Darby');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (846695, 'Aluf Mishne', 'Tynan');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (997292, 'Sgan Aluf Bakhir', 'Georg');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (656800, 'Sgan Aluf Mishne', 'Dasi');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (879092, 'Sgan Aluf Bakhir', 'Barnaby');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (754097, 'Tzir Aluf', 'Natasha');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (450628, 'Seren', 'Mella');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (938977, 'Sgan Aluf Mishne', 'Miranda');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (815760, 'Tat Aluf', 'Rochell');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (979535, 'Tzir Aluf', 'Sherlock');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (718466, 'Aluf Mishne', 'Alexi');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (208116, 'Sgan Aluf', 'Pierson');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (104124, 'Aluf Mishne', 'Humbert');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (543672, 'Sgan Aluf Mishne', 'Emmit');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (462476, 'Sgan Aluf Mishne', 'Fleming');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (992613, 'Seren', 'Niki');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (186954, 'Rav Seren', 'Daphna');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (223681, 'Tzir Aluf', 'Janessa');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (425102, 'Seren', 'Brianna');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (862486, 'Rav Seren', 'Wynn');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (302073, 'Tzir Aluf', 'Charil');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (221997, 'Tzir Aluf', 'Jenni');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (692787, 'Sgan Aluf Bakhir', 'Gino');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (231645, 'Seren', 'Morna');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (643183, 'Tat Aluf', 'Nester');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (102879, 'Seren', 'Loraine');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (792267, 'Sgan Aluf Mishne', 'Cathrin');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (703530, 'Aluf', 'Jody');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (146927, 'Aluf', 'Ezechiel');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (180150, 'Tzir Aluf', 'Dennie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (453029, 'Tzir Aluf', 'Edgardo');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (453546, 'Sgan Aluf Bakhir', 'Jacquenetta');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (216011, 'Aluf Mishne', 'Calv');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (865511, 'Seren', 'Ynez');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (180136, 'Rav Seren', 'Bryant');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (660583, 'Sgan Aluf Mishne', 'Jessee');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (148456, 'Sgan Aluf', 'Drusie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (849334, 'Tzir Aluf', 'Shayla');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (837158, 'Aluf Mishne', 'Nixie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (397276, 'Sgan Aluf Mishne', 'Kayla');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (542961, 'Rav Seren', 'Claudina');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (689669, 'Sgan Aluf', 'Sayre');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (771186, 'Seren', 'Genevieve');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (903906, 'Tzir Aluf', 'Cesya');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (139929, 'Sgan Aluf', 'Lora');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (981809, 'Tat Aluf', 'Armand');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (290890, 'Sgan Aluf Mishne', 'Zora');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (890018, 'Aluf Mishne', 'Allis');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (373459, 'Sgan Aluf Bakhir', 'Man');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (293735, 'Sgan Aluf', 'Veronike');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (323027, 'Aluf Mishne', 'Maria');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (644627, 'Tat Aluf', 'Kathe');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (406947, 'Tat Aluf', 'Dwight');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (565813, 'Sgan Aluf Bakhir', 'Clemente');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (159867, 'Aluf', 'Gabriellia');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (663623, 'Aluf Mishne', 'Selene');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (499785, 'Tzir Aluf', 'Mikaela');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (346224, 'Rav Seren', 'Kelcy');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (307989, 'Aluf Mishne', 'Meredeth');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (714902, 'Sgan Aluf Mishne', 'Kiel');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (268843, 'Seren', 'Salaidh');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (367325, 'Tzir Aluf', 'Clary');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (891930, 'Sgan Aluf Mishne', 'Chickie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (582697, 'Aluf', 'Colin');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (981296, 'Aluf', 'Rees');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (449186, 'Tat Aluf', 'Luce');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (438933, 'Sgan Aluf', 'Farlie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (354225, 'Aluf', 'Myer');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (817840, 'Rav Seren', 'Lisbeth');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (549507, 'Aluf', 'Glynis');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (162473, 'Tat Aluf', 'Rena');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (891350, 'Tzir Aluf', 'Dulcy');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (120494, 'Aluf Mishne', 'Evonne');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (681962, 'Seren', 'Dyana');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (316349, 'Rav Seren', 'Lyda');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (738702, 'Sgan Aluf Mishne', 'Mattias');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (670289, 'Sgan Aluf Bakhir', 'Renard');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (173607, 'Sgan Aluf', 'Rana');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (930358, 'Rav Seren', 'Fara');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (601156, 'Tat Aluf', 'Geoffrey');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (295296, 'Sgan Aluf Bakhir', 'Mauricio');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (560849, 'Sgan Aluf', 'Iona');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (540566, 'Seren', 'Dianemarie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (955081, 'Sgan Aluf', 'Darwin');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (691278, 'Rav Seren', 'Cristen');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (786445, 'Aluf', 'Druci');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (167869, 'Seren', 'Reggie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (174419, 'Aluf Mishne', 'Aldus');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (461188, 'Aluf Mishne', 'Gusti');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (217257, 'Sgan Aluf Bakhir', 'Arliene');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (778417, 'Sgan Aluf', 'Cozmo');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (797685, 'Tzir Aluf', 'Abelard');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (313242, 'Sgan Aluf Bakhir', 'Adolphe');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (658665, 'Sgan Aluf Bakhir', 'Iormina');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (259909, 'Seren', 'Vittoria');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (935961, 'Aluf Mishne', 'Cherry');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (698372, 'Rav Seren', 'Ruprecht');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (204079, 'Sgan Aluf Mishne', 'Conney');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (850604, 'Tat Aluf', 'Lezley');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (831564, 'Seren', 'Dore');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (653108, 'Sgan Aluf Bakhir', 'Nanny');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (991900, 'Rav Seren', 'Loni');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (306160, 'Tat Aluf', 'Isahella');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (246639, 'Tzir Aluf', 'Riley');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (166751, 'Sgan Aluf', 'Cecilius');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (389685, 'Aluf Mishne', 'Carey');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (816841, 'Tat Aluf', 'Greggory');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (591158, 'Sgan Aluf Bakhir', 'Georgi');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (694896, 'Tzir Aluf', 'Bob');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (500008, 'Tzir Aluf', 'Paolina');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (266896, 'Sgan Aluf', 'Truman');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (229857, 'Aluf', 'Jedd');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (667989, 'Tat Aluf', 'Johnny');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (805321, 'Rav Seren', 'Elyse');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (109092, 'Seren', 'Eloisa');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (349590, 'Sgan Aluf', 'Bili');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (547112, 'Tat Aluf', 'Ezmeralda');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (105936, 'Aluf', 'Massimiliano');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (643948, 'Tzir Aluf', 'Rosabella');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (122510, 'Sgan Aluf Mishne', 'Gun');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (391398, 'Tzir Aluf', 'Constantina');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (814856, 'Seren', 'Michaeline');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (817293, 'Tzir Aluf', 'Darryl');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (259716, 'Aluf', 'Vanya');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (277032, 'Sgan Aluf Mishne', 'Lyda');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (206999, 'Tzir Aluf', 'Zachary');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (379657, 'Sgan Aluf Mishne', 'Fidelia');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (753740, 'Tat Aluf', 'Alicia');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (781208, 'Tat Aluf', 'Stacie');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (191031, 'Tzir Aluf', 'Parrnell');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (115346, 'Tzir Aluf', 'Terese');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (945605, 'Tzir Aluf', 'Indira');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (830258, 'Tat Aluf', 'Caddric');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (966540, 'Sgan Aluf', 'Ketty');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (879617, 'Aluf', 'Keen');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (239579, 'Sgan Aluf', 'Helaine');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (249159, 'Aluf', 'Blaine');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (725817, 'Seren', 'Elsbeth');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (171217, 'Sgan Aluf', 'Beryle');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (626172, 'Aluf', 'Elliott');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (880868, 'Sgan Aluf Mishne', 'Cathrine');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (561933, 'Rav Seren', 'Brit');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (825285, 'Tat Aluf', 'Rickard');
insert into Solider (Personnel_ID, Rank, Name_Of_Soldier) values (373607, 'Sgan Aluf Mishne', 'Dianemarie');
